### ISSUE TITLE
Interested to implement a new feature (Input :- image , text ; Output:- similar image patches & llm answer)

### ISSUE THREAD

**Issue by chakka-guna-sekhar-venkata-chennaiah** [tonywu71/colpali-cookbooks#15] opened 2024-12-22 03:04 UTC
If the user given any image as input then we can use vision encoder which we used in the offline phase . So, that we get the embeddings of that image right. Then we need to apply linear projection for getting down to the 128 to match the image patch embedding dimensions. As mentioned above, we need to calculate the cosine similarity for the user input image embedding with the cluster embedding . Then we need to select top 3 clusters and then calculate the cosine similarity between user input image embedding with that selected cluster embeddings. The main usage of clustering is to reduce the millions of calculation (lets us think that we have million image patches). In a single shot not only text from generated from the answer we will also returns the patch which is similiar to the user image patch. The main reason for adding this feature that if any building rag on aircraft manual maintenance materials, then works can easily take a photo from their workstation and can easily chat with the model. In that returning only text may leads to not trusting the model (because of stochastic nature of llm) . If we return the similar patch from the source will helps them to trust the system and we can create 100% validation

**Comment by tonywu71** [comment] 2024-12-25 13:40
Duplicate of https://github.com/illuin-tech/colpali/issues/160.

**Closed as completed by tonywu71** 2024-12-25 13:40 UTC
